### PR TITLE
Dev into main for release

### PR DESCRIPTION
**Pull request by lornebb**
Push from develop into main for release.

### CODE REVIEW

**Comment by lornebb** [comment]
Oh man, @Nick-Dalby - Been looking at this all morning... I need another set of eyes on this, can you see why the build is failing? It says the NPM package is failing, but I can't see anything wrong with it (yet!)

**Comment by Nick-Dalby** [comment]
I just tried a local build and it doesn't like the 'getBandcampSongs.tsx' file 

...its commented out anyway. I deleted it and the build worked.

**Comment by Nick-Dalby** [comment]
wait...I hadnt pulled the latest

package.json line 32 is a duplicate without an ending comma
delete that  line
...there's also a bunch of other duplicates in the package.json (??)
delete the dupes

also delete the icons folder and its contents and the 'getBandcampSongs.tsx' file

build should work then

**Comment by Nick-Dalby** [comment]
I guess running a local build first gives better error warnings than what you get from netlify

...it'll just tell you what to fix

**Comment by lornebb** [comment]
I didn't get any of those errors... SO weird. I guarantee you that I didn't pull the latest or something. haha. ...hold my beer.

**Comment by lornebb** [comment]
Yup... entirely my own fault. Thanks man!

**Comment by lornebb** [comment]
I clearly did a shady conflict resolve!! haha. Sorry for that.

**Comment by lornebb** [comment]
@Nick-Dalby ready for review! :)

**Review by Nick-Dalby — APPROVED** [review]
💪

**Pull request merged**
