### PR TITLE
update production Nov 22

### PR DESCRIPTION
**Pull request by lornebb**
feats:
new background
new year component
new footer
new hero banner

fix:
typings on floating bananas
hero banner image is now hosted, rather than uploaded to repo.

### CODE REVIEW

**Comment by lornebb** [comment]
@Nick-Dalby - ready for review to merge to production! 

You should be immensely proud of your contribution to this production build. It looks SO good, thanks to you! :) 

On behalf of the whole band of kongs, thank you! :) 

btw, no one believes me when I use band: https://www.grammar-monster.com/collective_nouns/collective-noun-for-gorillas.html

**Review by Nick-Dalby — APPROVED** [review]
looks good!

**Comment by Nick-Dalby** [comment]
I still don't get the typing thing in the floatingbananna component either...is it common in production to just slap a ts-ignore on stuff like that?

**Comment by Nick-Dalby** [comment]
...this should have auto-deployed right?

Is there something wrong with the URL redirect?

**Comment by lornebb** [comment]
> I still don't get the typing thing in the floatingbananna component either...is it common in production to just slap a ts-ignore on stuff like that?

I tried everything to find the right type for it. It's actually more uncommon for the package provider to not have types for .nested aspects of their code base. So, yeah, its (very) bad practise, but it wont break anything for now.

**Comment by lornebb** [comment]
This was the error. Gonna look into it now.

Screenshot 2022-11-29 at 13 13 01

**Comment by lornebb** [comment]
https://app.netlify.com/sites/sok-banana-stand/deploys/6385d0962955640008c07944

**Comment by lornebb** [comment]
fixed. and live ✅

**Comment by Nick-Dalby** [comment]
hmm weird...maybe just needs a manual deploy?

I just checked, it's a separate npm install for the threejs types:
https://www.npmjs.com/package/@types/three

**Comment by Nick-Dalby** [comment]
I've just noticed the cold start of the render is a bit jarring...let me see about adding a transition while it loads

like a star wars style circle wipe maybe?
https://www.transition.style/#in:circle:center

**Pull request merged**
